name: Release

on:
  push:
    branches:
      - main


permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make changes
        if: ${{ steps.release.outputs.release_created }}  
        run: |
          # 这里是你需要进行更改的步骤
          echo "Some changes" > some_file.txt
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}